### ISSUE TITLE
Create a Home page

### ISSUE THREAD

**Issue by Jagannath8** [Jagannath8/shopping#1]
Create an attractive home page

**Comment by SamikshaSankar** [comment]
Have you made any design?Like how you want?

**Comment by Jagannath8** [comment]
![image](https://user-images.githubusercontent.com/64650848/126079586-5cd42085-6a27-4a9d-a748-f6e2c8e224f8.png)

@SamikshaSankar 
Somewhat like this 
Header should only contain home, about us, products, contact us, login/signup

**Comment by Amrutha1101** [comment]
Can I take up this issue ?

**Comment by Jagannath8** [comment]
Sure @Amrutha1101. Make the UI attractive

**Comment by Jagannath8** [comment]
Hey @Amrutha1101 What is the status?

**Comment by Amrutha1101** [comment]
I'm not good at web designing  and it's home page so I'll be unassigning sorry. May be someone will do it better.

**Comment by Jagannath8** [comment]
Its okay @Amrutha1101

**Comment by aditya687** [comment]
Please assign me this issue I will design a beautiful and responsive home page @Jagannath8

**Comment by Jagannath8** [comment]
Sure @aditya687 Go ahead!
