### ISSUE TITLE
Design Report an issue page for this website.

### ISSUE THREAD

**Issue by Ayonijakaushik19** [Jagannath8/shopping#17]

**Comment by comnk** [comment]
can I work on this issue?

**Comment by Jagannath8** [comment]
Sure @comnk

**Comment by comnk** [comment]
does it need to be in a separate folder? and where will the request go to (which email?)

**Comment by Jagannath8** [comment]
yes @comnk make a separate folder for it
email - jagannath9611@gmail.com

**Comment by comnk** [comment]
do we need to send the person a response back about the issue, or is there no need for response?

**Comment by comnk** [comment]
should it be in the header or the footer?

**Comment by Jagannath8** [comment]
@comnk Place it in footer and no need of respone

**Comment by vchsi** [comment]
Hi Jagannath8 and Ayonijakaushik19, 
I am a new contributor and I found this project from a forum for best projects for beginners. I have done some web development before, including HTML,CSS,JS and Flask and some Node.js and I have used email services such as SMTPLIB and IMAP. May I have this issue so I can start my Open Source contributions?

**Comment by aditya687** [comment]
Can you assign this issue? @Jagannath8

**Comment by Jagannath8** [comment]
@vchsi @aditya687 This issue has already been assigned to @comnk 
Please take up other issues

**Comment by comnk** [comment]
am I able to use flask or should I just use php?

**Comment by Jagannath8** [comment]
@comnk  Use flask

**Comment by comnk** [comment]
is there any way I can get flask_mail extension from flask to help with the emailing part (because after issue is reported an email is sent)?

**Comment by comnk** [comment]
does the flask run on locahost or which ip address?

**Comment by comnk** [comment]
do you have a web server to run the website on. Currently the flask runs on 127.0.0.1

**Comment by Jagannath8** [comment]
Okay @comnk 
You make PR, I will check

**Comment by comnk** [comment]
submitted PR for this issue
