### ISSUE TITLE
Create About us page

### ISSUE THREAD

**Issue by Jagannath8** [Jagannath8/shopping#2]

**Comment by Amrutha1101** [comment]
Can I work on this issue under Devincept'21

**Comment by Jagannath8** [comment]
Ya sure @Amrutha1101

**Comment by Amrutha1101** [comment]
May I know if you have you have any content to put in about us page??

**Comment by Jagannath8** [comment]
@Amrutha1101 About us page must have short description, vision & mission, why to choose us

**Comment by Amrutha1101** [comment]
Shall I place the about us button here later a navbar can be created ??
![Screenshot (164)](https://user-images.githubusercontent.com/63070698/126097453-f2851345-6201-4cfc-ac45-650698bb456f.png)

**Comment by Jagannath8** [comment]
No, don't place it here @Amrutha1101 
We will add it on home page later
Just add About us folder containing html, css files
