### ISSUE TITLE
Add some badges to the README

### ISSUE THREAD

**Issue by Umesh-01** [Jagannath8/shopping#37]
### Description
Add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

### Solution
I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

**Comment by Umesh-01** [comment]
@Jagannath8 should I work on this??

**Comment by Jagannath8** [comment]
Sure! @Umesh-01

**Comment by Umesh-01** [comment]
hi @Jagannath8 , what this DCP'21 badge means??

**Comment by Umesh-01** [comment]
Is it a open source program ??

Can I participate in this?? 🤔

**Comment by Umesh-01** [comment]
and yes, check my PR.. 😄

**Comment by Jagannath8** [comment]
@Umesh-01 DCP means DevIncept Open Source Contribution Program.
Are you not a part of it?
Sure I'll check your PR

**Comment by Umesh-01** [comment]
> @Umesh-01 DCP means DevIncept Open Source Contribution Program.
> Are you not a part of it?
> Sure I'll check your PR

No, I am not a part of it.
Can I participate now, Is the registrations open??

**Comment by Jagannath8** [comment]
No @Umesh-01 applications are closed
