### ISSUE TITLE
Style: Product card

### ISSUE THREAD

**Issue by shreyshreyansh** [Jagannath8/shopping#44]
Style of the Product cards can be improved

![aaa](https://user-images.githubusercontent.com/53744971/127612845-73060344-8aff-4f74-b846-5aed92bd330e.png)

**Comment by Jagannath8** [comment]
Go ahead @shreyshreyansh

**Comment by Jagannath8** [comment]
@shreyshreyansh Fill this form for calculation of points
https://docs.google.com/forms/d/e/1FAIpQLSeHqAaYHdWPfzRdkdmEwCmM7YK6VLl-otseD0fQr3rFDget5w/viewform
