### ISSUE TITLE
Make all Social Media links working

### ISSUE THREAD

**Issue by Jagannath8** [Jagannath8/shopping#48]
- Make all Social Media links working in home, product, contact page
- Take all links from my github profile

**Comment by jay-2000** [comment]
can i work on this issue @Jagannath8 under DCP'21
also ,do let me know where can i find your facebook and twitter handles since its not available in github profile

**Comment by Jagannath8** [comment]
Twitter: https://twitter.com/Jaganna38568564
Facebook: https://www.facebook.com/jagannath.08
