### ISSUE TITLE
Design an attractive logo

### ISSUE THREAD

**Issue by Jagannath8** [Jagannath8/shopping#5]

**Comment by Ayonijakaushik19** [comment]
I want to work on this issue under DCP'21, please assign me this @Jagannath8

**Comment by Ayonijakaushik19** [comment]
Hi, @Jagannath8  I have created some unique and attractive Logos for this website.

**1**
![image](https://user-images.githubusercontent.com/84201769/126075743-cce515b2-227b-4acd-ab35-b5487eafac61.png)

**2**
![image](https://user-images.githubusercontent.com/84201769/126075769-72364ad2-82ec-406d-937a-6026c8995adc.png)

**3**
![image](https://user-images.githubusercontent.com/84201769/126075776-6c9b7be3-a7f9-4c00-9bd5-a1fc7f59940e.png)

**4**
![image](https://user-images.githubusercontent.com/84201769/126075795-54a68c66-9b2b-4dd0-b44a-4e53f26ff983.png)

**5**
![image](https://user-images.githubusercontent.com/84201769/126075811-beb129c5-1fd9-4dc9-9cc9-5698821501b4.png)

**6**
![image](https://user-images.githubusercontent.com/84201769/126075821-3c1e7b34-f9de-46be-bb3f-a287160401c0.png)

**7**
![image](https://user-images.githubusercontent.com/84201769/126075835-946fe14a-0e27-4a6d-9cf1-3322ca11e655.png)

**8**
![image](https://user-images.githubusercontent.com/84201769/126075843-de87f866-6631-4785-a823-3a892b009ed1.png)

**9**
![image](https://user-images.githubusercontent.com/84201769/126075854-3d1be369-5972-4081-ab06-0f5b87ff3589.png)

**Comment by Ayonijakaushik19** [comment]
Please Suggest which looks fine to you

**Comment by Jagannath8** [comment]
3rd logo seems perfect to me @Ayonijakaushik19

**Comment by Ayonijakaushik19** [comment]
Hi, @Jagannath8  I have raised a PR for this issue please have a look.

**Comment by Jagannath8** [comment]
@Ayonijakaushik19  Do fill this form: https://docs.google.com/forms/d/e/1FAIpQLSeHqAaYHdWPfzRdkdmEwCmM7YK6VLl-otseD0fQr3rFDget5w/viewform
