### ISSUE TITLE
Creating Code of conduct file

### ISSUE THREAD

**Issue by aakankshabhende** [Jagannath8/shopping#6]
Creating a Code of Conduct which everyone must abide by and mentioning the Scope of this Code of Conduct.

I want to work on this under DCP'21, please assign me this @Jagannath8

**Comment by Jagannath8** [comment]
Go ahead @aakankshabhende

**Comment by Jagannath8** [comment]
@aakankshabhende  Do fill this form: https://docs.google.com/forms/d/e/1FAIpQLSeHqAaYHdWPfzRdkdmEwCmM7YK6VLl-otseD0fQr3rFDget5w/viewform
