### ISSUE TITLE
Design Contact Us page for this website

### ISSUE THREAD

**Issue by Ayonijakaushik19** [Jagannath8/shopping#9]
Hi, @Jagannath8 I want to work on this issue under DCP'21, please assign this to me.

**Comment by Jagannath8** [comment]
Hey @Ayonijakaushik19  What is the status?

**Comment by aditya687** [comment]
Please assign me this issue @Jagannath8

**Comment by Jagannath8** [comment]
> Please assign me this issue @Jagannath8

3 issues has already been assigned to you @aditya687 
Once you make PR for previous issues, you can work on this

**Comment by aditya687** [comment]
Can I take a try for this issue @Jagannath8 ?
